services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - postgre_vol:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - pg_net
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    volumes:
      - pgadmin_vol:/var/lib/pgadmin
    networks:
      - pg_net
 
volumes:
  postgre_vol:
  pgadmin_vol:
  
networks:
  pg_net:


  



